project_id = "ftyyjxrrmxlssghrrlzg"

[functions.brevo-subscribe]
verify_jwt = false

[functions.process-preorder]
verify_jwt = false

[functions.track-abandoned-cart]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false