/**
 * Generates public/sitemap.xml from src/content/site-urls.ts.
 *
 * Runs automatically before every Vite build (see vite.config.ts).
 * Can also be run manually:  node scripts/generate-sitemap.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

async function loadEntries() {
  const { transformWithEsbuild } = await import("vite");
  const { readFileSync } = await import("node:fs");
  const tsPath = resolve(ROOT, "src/content/site-urls.ts");
  const source = readFileSync(tsPath, "utf8");
  const { code } = await transformWithEsbuild(source, tsPath, {
    loader: "ts",
    format: "esm",
    target: "es2022",
  });
  const dataUrl =
    "data:text/javascript;base64," + Buffer.from(code).toString("base64");
  const mod = await import(dataUrl);
  return {
    SITE_URL: mod.SITE_URL,
    entries: mod.getAllSitemapEntries(),
  };
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function renderUrl(entry, siteUrl) {
  const lines = [];
  lines.push("  <url>");
  lines.push(`    <loc>${escapeXml(siteUrl + entry.path)}</loc>`);
  if (entry.lastmod) lines.push(`    <lastmod>${entry.lastmod}</lastmod>`);
  if (entry.changefreq)
    lines.push(`    <changefreq>${entry.changefreq}</changefreq>`);
  if (entry.priority !== undefined)
    lines.push(`    <priority>${entry.priority.toFixed(2)}</priority>`);
  if (entry.images?.length) {
    for (const img of entry.images) {
      lines.push("    <image:image>");
      lines.push(`      <image:loc>${escapeXml(img.loc)}</image:loc>`);
      if (img.title)
        lines.push(`      <image:title>${escapeXml(img.title)}</image:title>`);
      if (img.caption)
        lines.push(
          `      <image:caption>${escapeXml(img.caption)}</image:caption>`,
        );
      lines.push("    </image:image>");
    }
  }
  lines.push("  </url>");
  return lines.join("\n");
}

function buildSitemap(entries, siteUrl) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Auto-generated by scripts/generate-sitemap.mjs — do not edit by hand. -->",
    "<!-- Source: src/content/site-urls.ts -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    "",
    entries.map((e) => renderUrl(e, siteUrl)).join("\n"),
    "",
    "</urlset>",
    "",
  ].join("\n");
}

function buildSitemapIndex(today, siteUrl) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Auto-generated by scripts/generate-sitemap.mjs -->",
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    "  <sitemap>",
    `    <loc>${siteUrl}/sitemap.xml</loc>`,
    `    <lastmod>${today}</lastmod>`,
    "  </sitemap>",
    "  <sitemap>",
    `    <loc>${siteUrl}/sitemap-images.xml</loc>`,
    `    <lastmod>${today}</lastmod>`,
    "  </sitemap>",
    "</sitemapindex>",
    "",
  ].join("\n");
}

export async function generateSitemap() {
  const { SITE_URL, entries } = await loadEntries();
  const xml = buildSitemap(entries, SITE_URL);
  const today = new Date().toISOString().slice(0, 10);
  const indexXml = buildSitemapIndex(today, SITE_URL);

  const outDir = resolve(ROOT, "public");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, "sitemap.xml"), xml, "utf8");
  writeFileSync(resolve(outDir, "sitemap-index.xml"), indexXml, "utf8");

  return { count: entries.length };
}

// Run when executed directly
const isDirect =
  import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (isDirect) {
  generateSitemap()
    .then(({ count }) =>
      console.log(`✓ sitemap.xml generated with ${count} URLs`),
    )
    .catch((err) => {
      console.error("✗ sitemap generation failed:", err);
      process.exit(1);
    });
}
